name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: jrschumacher/go-actions/release@v3
        with:
          release-token: ${{ secrets.RELEASE_TOKEN }}
